In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## exploration

In [2]:
df=pd.read_csv('ml_data.csv')

In [3]:
df.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [4]:
df.columns


Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [5]:
df.sample()

Suburb         Address  Rooms Type     Price Method   SellerG  \
4786  Port Melbourne  405/2 Rouse St      1    u  600000.0      S  Marshall   

            Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
4786  25/02/2017       3.8    3207.0  ...       1.0  1.0    6866.0   

      BuildingArea  YearBuilt   CouncilArea Lattitude  Longtitude  \
4786          63.0     2010.0  Port Phillip  -37.8443    144.9437   

                 Regionname Propertycount  
4786  Southern Metropolitan        8648.0  

[1 rows x 21 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  object 
 1   Address        13580 non-null  object 
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  object 
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object 
 6   SellerG        13580 non-null  object 
 7   Date           13580 non-null  object 
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object 
 17  Lattitude      13580 non-null  float64
 18  Longti

In [7]:
df.shape


(13580, 21)

In [8]:
df.describe()

Rooms         Price      Distance      Postcode      Bedroom2  \
count  13580.000000  1.358000e+04  13580.000000  13580.000000  13580.000000   
mean       2.937997  1.075684e+06     10.137776   3105.301915      2.914728   
std        0.955748  6.393107e+05      5.868725     90.676964      0.965921   
min        1.000000  8.500000e+04      0.000000   3000.000000      0.000000   
25%        2.000000  6.500000e+05      6.100000   3044.000000      2.000000   
50%        3.000000  9.030000e+05      9.200000   3084.000000      3.000000   
75%        3.000000  1.330000e+06     13.000000   3148.000000      3.000000   
max       10.000000  9.000000e+06     48.100000   3977.000000     20.000000   

           Bathroom           Car       Landsize  BuildingArea    YearBuilt  \
count  13580.000000  13518.000000   13580.000000   7130.000000  8205.000000   
mean       1.534242      1.610075     558.416127    151.967650  1964.684217   
std        0.691712      0.962634    3990.669241    541.014538    37.273762   
min        0.000000      0.000000       0.000000      0.000000  1196.000000   
25%        1.000000      1.000000     177.000000     93.000000  1940.000000   
50%        1.000000      2.000000     440.000000    126.000000  1970.000000   
75%        2.000000      2.000000     651.000000    174.000000  1999.000000   
max        8.000000     10.000000  433014.000000  44515.000000  2018.000000   

          Lattitude    Longtitude  Propertycount  
count  13580.000000  13580.000000   13580.000000  
mean     -37.809203    144.995216    7454.417378  
std        0.079260      0.103916    4378.581772  
min      -38.182550    144.431810     249.000000  
25%      -37.856822    144.929600    4380.000000  
50%      -37.802355    145.000100    6555.000000  
75%      -37.756400    145.058305   10331.000000  
max      -37.408530    145.526350   21650.000000

In [9]:
#what is the average land  size rounded up to nearest integer
avg_land=df.Landsize.mean()

In [10]:
round(avg_land)

558

In [11]:
# how old is the newset home
import datetime
newest_home=df['YearBuilt'].max()
print(2024-newest_home)

6.0


## data cleaning

In [12]:
df.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [13]:
cdf=df.copy()

In [14]:
cdf.shape

(13580, 21)

In [15]:
cdf.dropna(axis=0,inplace=True)

In [16]:
cdf

Suburb          Address  Rooms Type      Price Method  \
1        Abbotsford  25 Bloomburg St      2    h  1035000.0      S   
2        Abbotsford     5 Charles St      3    h  1465000.0     SP   
4        Abbotsford      55a Park St      4    h  1600000.0     VB   
6        Abbotsford     124 Yarra St      3    h  1876000.0      S   
7        Abbotsford    98 Charles St      2    h  1636000.0      S   
...             ...              ...    ...  ...        ...    ...   
12205    Whittlesea    30 Sherwin St      3    h   601000.0      S   
12206  Williamstown      75 Cecil St      3    h  1050000.0     VB   
12207  Williamstown    2/29 Dover Rd      1    u   385000.0     SP   
12209       Windsor  201/152 Peel St      2    u   560000.0     PI   
12212    Yarraville  54 Pentland Pde      6    h  2450000.0     VB   

             SellerG        Date  Distance  Postcode  ...  Bathroom  Car  \
1             Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0   
2             Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0   
4             Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0   
6             Nelson   7/05/2016       2.5    3067.0  ...       2.0  0.0   
7             Nelson   8/10/2016       2.5    3067.0  ...       1.0  2.0   
...              ...         ...       ...       ...  ...       ...  ...   
12205            Ray  29/07/2017      35.5    3757.0  ...       2.0  1.0   
12206       Williams  29/07/2017       6.8    3016.0  ...       1.0  0.0   
12207       Williams  29/07/2017       6.8    3016.0  ...       1.0  1.0   
12209  hockingstuart  29/07/2017       4.6    3181.0  ...       1.0  1.0   
12212        Village  29/07/2017       6.3    3013.0  ...       3.0  2.0   

       Landsize  BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
1         156.0         79.00     1900.0        Yarra -37.80790   144.99340   
2         134.0        150.00     1900.0        Yarra -37.80930   144.99440   
4         120.0        142.00     2014.0        Yarra -37.80720   144.99410   
6         245.0        210.00     1910.0        Yarra -37.80240   144.99930   
7         256.0        107.00     1890.0        Yarra -37.80600   144.99540   
...         ...           ...        ...          ...       ...         ...   
12205     972.0        149.00     1996.0   Whittlesea -37.51232   145.13282   
12206     179.0        115.00     1890.0  Hobsons Bay -37.86558   144.90474   
12207       0.0         35.64     1967.0  Hobsons Bay -37.85588   144.89936   
12209       0.0         61.60     2012.0  Stonnington -37.85581   144.99025   
12212    1087.0        388.50     1920.0  Maribyrnong -37.81038   144.89389   

                  Regionname Propertycount  
1      Northern Metropolitan        4019.0  
2      Northern Metropolitan        4019.0  
4      Northern Metropolitan        4019.0  
6      Northern Metropolitan        4019.0  
7      Northern Metropolitan        4019.0  
...                      ...           ...  
12205      Northern Victoria        2170.0  
12206   Western Metropolitan        6380.0  
12207   Western Metropolitan        6380.0  
12209  Southern Metropolitan        4380.0  
12212   Western Metropolitan        6543.0  

[6196 rows x 21 columns]

In [17]:
cdf.corr(numeric_only=True)

Rooms     Price  Distance  Postcode  Bedroom2  Bathroom  \
Rooms          1.000000  0.533505  0.283885  0.051237  0.951793  0.613853   
Price          0.533505  1.000000 -0.148867  0.125539  0.514561  0.503922   
Distance       0.283885 -0.148867  1.000000  0.405729  0.290242  0.124530   
Postcode       0.051237  0.125539  0.405729  1.000000  0.053770  0.109804   
Bedroom2       0.951793  0.514561  0.290242  0.053770  1.000000  0.617751   
Bathroom       0.613853  0.503922  0.124530  0.109804  0.617751  1.000000   
Car            0.422526  0.261507  0.273615  0.043713  0.425726  0.340808   
Landsize       0.098755  0.081419  0.059369  0.025807  0.097172  0.076295   
BuildingArea   0.608215  0.530574  0.159603  0.078483  0.593000  0.534425   
YearBuilt     -0.068122 -0.304633  0.246291  0.024375 -0.056343  0.157820   
Lattitude      0.016049 -0.213574 -0.094494 -0.425172  0.021309 -0.072020   
Longtitude     0.088031  0.211760  0.221861  0.471305  0.085895  0.116103   
Propertycount -0.111422 -0.046410 -0.083969  0.064534 -0.109401 -0.067126   

                    Car  Landsize  BuildingArea  YearBuilt  Lattitude  \
Rooms          0.422526  0.098755      0.608215  -0.068122   0.016049   
Price          0.261507  0.081419      0.530574  -0.304633  -0.213574   
Distance       0.273615  0.059369      0.159603   0.246291  -0.094494   
Postcode       0.043713  0.025807      0.078483   0.024375  -0.425172   
Bedroom2       0.425726  0.097172      0.593000  -0.056343   0.021309   
Bathroom       0.340808  0.076295      0.534425   0.157820  -0.072020   
Car            1.000000  0.117647      0.334282   0.108714   0.011973   
Landsize       0.117647  1.000000      0.084825   0.026518   0.005610   
BuildingArea   0.334282  0.084825      1.000000   0.005836  -0.037904   
YearBuilt      0.108714  0.026518      0.005836   1.000000   0.057108   
Lattitude      0.011973  0.005610     -0.037904   0.057108   1.000000   
Longtitude     0.054699  0.032918      0.103613  -0.002114  -0.357988   
Propertycount -0.046487 -0.017784     -0.066144  -0.000797   0.057225   

               Longtitude  Propertycount  
Rooms            0.088031      -0.111422  
Price            0.211760      -0.046410  
Distance         0.221861      -0.083969  
Postcode         0.471305       0.064534  
Bedroom2         0.085895      -0.109401  
Bathroom         0.116103      -0.067126  
Car              0.054699      -0.046487  
Landsize         0.032918      -0.017784  
BuildingArea     0.103613      -0.066144  
YearBuilt       -0.002114      -0.000797  
Lattitude       -0.357988       0.057225  
Longtitude       1.000000       0.073856  
Propertycount    0.073856       1.000000

In [19]:
#selecting the prdeiction target
y=cdf.Price

In [39]:
features=['Rooms','Bedroom2','Bathroom','Landsize','BuildingArea','YearBuilt','Lattitude','Longtitude']

In [23]:
X=cdf[features]

In [24]:
X.describe()

Rooms     Bedroom2     Bathroom      Landsize  BuildingArea  \
count  6196.000000  6196.000000  6196.000000   6196.000000   6196.000000   
mean      2.931407     2.902034     1.576340    471.006940    141.568645   
std       0.971079     0.970055     0.711362    897.449881     90.834824   
min       1.000000     0.000000     1.000000      0.000000      0.000000   
25%       2.000000     2.000000     1.000000    152.000000     91.000000   
50%       3.000000     3.000000     1.000000    373.000000    124.000000   
75%       4.000000     3.000000     2.000000    628.000000    170.000000   
max       8.000000     9.000000     8.000000  37000.000000   3112.000000   

         YearBuilt    Lattitude   Longtitude  
count  6196.000000  6196.000000  6196.000000  
mean   1964.081988   -37.807904   144.990201  
std      38.105673     0.075850     0.099165  
min    1196.000000   -38.164920   144.542370  
25%    1940.000000   -37.855438   144.926198  
50%    1970.000000   -37.802250   144.995800  
75%    2000.000000   -37.758200   145.052700  
max    2018.000000   -37.457090   145.526350

In [25]:
X.corr(numeric_only=True)

Rooms  Bedroom2  Bathroom  Landsize  BuildingArea  YearBuilt  \
Rooms         1.000000  0.951793  0.613853  0.098755      0.608215  -0.068122   
Bedroom2      0.951793  1.000000  0.617751  0.097172      0.593000  -0.056343   
Bathroom      0.613853  0.617751  1.000000  0.076295      0.534425   0.157820   
Landsize      0.098755  0.097172  0.076295  1.000000      0.084825   0.026518   
BuildingArea  0.608215  0.593000  0.534425  0.084825      1.000000   0.005836   
YearBuilt    -0.068122 -0.056343  0.157820  0.026518      0.005836   1.000000   
Lattitude     0.016049  0.021309 -0.072020  0.005610     -0.037904   0.057108   
Longtitude    0.088031  0.085895  0.116103  0.032918      0.103613  -0.002114   

              Lattitude  Longtitude  
Rooms          0.016049    0.088031  
Bedroom2       0.021309    0.085895  
Bathroom      -0.072020    0.116103  
Landsize       0.005610    0.032918  
BuildingArea  -0.037904    0.103613  
YearBuilt      0.057108   -0.002114  
Lattitude      1.000000   -0.357988  
Longtitude    -0.357988    1.000000

#built the model 

In [26]:
from sklearn.tree import DecisionTreeRegressor

In [27]:
#model
house_model=DecisionTreeRegressor(random_state=1)


In [28]:
house_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

## making prediction
## train data

In [29]:
X.head()

Rooms  Bedroom2  Bathroom  Landsize  BuildingArea  YearBuilt  Lattitude  \
1      2       2.0       1.0     156.0          79.0     1900.0   -37.8079   
2      3       3.0       2.0     134.0         150.0     1900.0   -37.8093   
4      4       3.0       1.0     120.0         142.0     2014.0   -37.8072   
6      3       4.0       2.0     245.0         210.0     1910.0   -37.8024   
7      2       2.0       1.0     256.0         107.0     1890.0   -37.8060   

   Longtitude  
1    144.9934  
2    144.9944  
4    144.9941  
6    144.9993  
7    144.9954

In [31]:
house_model.predict(X.head(3))

array([1035000., 1465000., 1600000.])

In [33]:
cdf['Price'].head(3)

1    1035000.0
2    1465000.0
4    1600000.0
Name: Price, dtype: float64

In [89]:
import pandas as pd

features = ['Rooms', 'Bedroom2', 'Bathroom', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude']
newhouse = [4, 2, 2, 250.0, 156, 2000, -37.8079, 144.9944]

newhouse_df = pd.DataFrame([newhouse], columns=features)


In [90]:
newhouse_df

Rooms  Bedroom2  Bathroom  Landsize  BuildingArea  YearBuilt  Lattitude  \
0      4         2         2     250.0           156       2000   -37.8079   

   Longtitude  
0    144.9944

In [91]:
house_model.predict(newhouse_df)

array([905000.])

In [58]:
newhouse2={'Rooms':4,'Bedroom2':4,'Bathroom':2,'Landsize':170,'BuildingArea':79,'YearBuilt':210,'Lattitude':-37.233,'Longtitude':144.9334}

In [59]:
newhouse2_df=pd.DataFrame([newhouse2])

In [60]:
house_model.predict(newhouse2_df)

array([1158000.])

#model validation

In [73]:
from sklearn.metrics import mean_absolute_error

In [74]:
php=house_model.predict(X)

In [75]:
php

array([1035000., 1465000., 1600000., ...,  385000.,  560000., 2450000.])

In [76]:
mean_absolute_error(y,php)

434.0703679793415

## mtheod 2: Train test split

In [81]:
from sklearn.model_selection import train_test_split
train_x,val_x,train_y,val_y=train_test_split(X,y,random_state=0)

In [82]:
#define a model
house_model=DecisionTreeRegressor()

In [83]:
house_model.fit(train_x,train_y)

DecisionTreeRegressor()

In [84]:
y.isna().sum()

0

In [85]:
X.isna().sum()

Rooms           0
Bedroom2        0
Bathroom        0
Landsize        0
BuildingArea    0
YearBuilt       0
Lattitude       0
Longtitude      0
dtype: int64

In [87]:
val_x

Rooms  Bedroom2  Bathroom  Landsize  BuildingArea  YearBuilt  \
4850       2       2.0       1.0      96.0          71.0     1880.0   
2307       2       2.0       1.0       0.0          70.0     1965.0   
10090      2       2.0       1.0     136.0          58.0     1892.0   
3645       3       3.0       2.0     205.0         184.0     1995.0   
4930       2       2.0       1.0     400.0          88.0     1955.0   
...      ...       ...       ...       ...           ...        ...   
8223       2       2.0       1.0       0.0          82.0     2011.0   
11190      3       3.0       2.0     590.0         151.0     1981.0   
8563       1       1.0       1.0    1175.0          35.0     1970.0   
1867       2       2.0       1.0     585.0          97.0     1950.0   
8375       2       2.0       2.0     208.0         145.0     1880.0   

       Lattitude  Longtitude  
4850   -37.85010   144.99530  
2307   -37.89020   144.99070  
10090  -37.85542   144.99571  
3645   -37.79930   145.02670  
4930   -37.73520   144.98520  
...          ...         ...  
8223   -37.73240   144.93770  
11190  -37.89628   145.22294  
8563   -37.78490   144.82720  
1867   -37.87920   145.09480  
8375   -37.84330   145.00240  

[1549 rows x 8 columns]

In [88]:
val_y

4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
           ...    
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64

In [92]:
#predict on train data

In [113]:
hp2=house_model.predict(train_x.head(3))

In [114]:
train_y.head(3)

10385    1060000.0
5805      390000.0
8488      502000.0
Name: Price, dtype: float64

In [115]:
val_x.head(3)

Rooms  Bedroom2  Bathroom  Landsize  BuildingArea  YearBuilt  \
4850       2       2.0       1.0      96.0          71.0     1880.0   
2307       2       2.0       1.0       0.0          70.0     1965.0   
10090      2       2.0       1.0     136.0          58.0     1892.0   

       Lattitude  Longtitude  
4850   -37.85010   144.99530  
2307   -37.89020   144.99070  
10090  -37.85542   144.99571

In [116]:
val_y.head(3)

4850     815000.0
2307     655000.0
10090    957500.0
Name: Price, dtype: float64

In [117]:
mean_absolute_error(val_y.head(3),hp2)

321833.3333333333

In [118]:
hp3=house_model.predict(val_x)

In [119]:
hp3

array([ 937500.,  680500., 1050000., ...,  240000., 1110000., 1320000.])

In [122]:
mean_absolute_error(val_y,hp3)

262124.26533247257

## trying different algo
randomforest regressor

In [123]:
from sklearn.ensemble import RandomForestRegressor

In [126]:
forest_model=RandomForestRegressor(random_state=1)

In [128]:
forest_model.fit(train_x,train_y)

RandomForestRegressor(random_state=1)

In [137]:
ran=forest_model.predict(val_x)

In [138]:
hp2

array([1060000.,  390000.,  502000.])

In [139]:
val_y.head(3)

4850     815000.0
2307     655000.0
10090    957500.0
Name: Price, dtype: float64

In [140]:
mean_absolute_error(val_y,ran)

191764.26509791263

In [141]:
# wirte a program to extract each digits from an sting in. the reverse order
# example-'abc123abc'->321
stirng='abc123abc'
a=set(stirng)

In [152]:
li1=list(a)

In [153]:
li1

['a', '3', '1', 'b', 'c', '2']

In [175]:
b=[]
for i in 'abc123bcd':
    if i.isdigit():
        b.append(i)
c=b[::-1]

In [176]:
c

['3', '2', '1']

In [177]:
s2=''

In [178]:
for i in c:
    s2+="".join(i)

In [179]:
s2

'321'